-- Find total Customers by countries
SELECT country, COUNT(DISTINCT customer_id) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total Customers by gender
SELECT gender, COUNT(DISTINCT customer_id) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT category, COUNT(DISTINCT product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs by each category?
SELECT category, AVG(product_cost) as avg_products_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_products_cost DESC;

-- What is the total revenue generated for each category?
SELECT p.category, SUM(s.sales_amount) as revenue
FROM gold.fact_sales AS s 
LEFT JOIN gold.dim_products AS p
	ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY revenue DESC;

-- Find total revenue generated by each customer
SELECT 
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) as revenue
FROM gold.fact_sales AS s 
LEFT JOIN gold.dim_customers AS c
	ON s.customer_key = c.customer_key
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY revenue DESC;

-- What is the distribution of sold items across countries?
SELECT c.country, SUM(s.quantity) as products_total
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
	ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY products_total DESC;
